### ISSUE TITLE
Homework 1 Possible Typo

### ISSUE THREAD

**Issue by tonofshell** [css-model/hw01#1]
On Question 3, Part c the question states to use a normal distribution to approximate the error, stated as `ϵ ∼ N(μ=0, θ^2=0.25)`. As a normal distribution is determined by a mean and a variance/standard deviation, I assume this is supposed to be `σ^2` to signify the variance for the normal distribution?

**Comment by bensoltoff** [comment]
Correct, that was a typo

**Comment by bensoltoff** [comment]
But do make sure in your code that you check to verify if the function expects the variance OR the standard deviation

**Comment by tonofshell** [comment]
Duly noted, thank you!
